include: package:very_good_analysis/analysis_options.3.0.0.yaml
analyzer:
  exclude:
    - build/**
    - lib/**.g.dart
    - lib/**.freezed.dart
  errors:
    invalid_annotation_target: ignore
linter:
  rules:
    file_names: false
    public_member_api_docs: false
    require_trailing_commas: false
