name: frog_firebase_auth_sample
description: A backend project sample with Firebase auth verification using dart_frog
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  dart_frog: ^0.0.1-dev
  dotenv: 4.0.1
  firebase_auth_admin_verify: 1.0.0
  freezed_annotation: 2.0.3
  http: 0.13.4
  json_annotation: 4.5.0
  postgres: 2.4.4

dev_dependencies:
  build_runner: 2.1.11
  freezed: 2.0.3+1
  json_serializable: 6.2.0
  mocktail: 0.3.0
  test: 1.21.1
  very_good_analysis: 3.0.0
